build.gradle
src/main/java/com/jfrog/ide/idea/NpmProject.java
src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
src/main/java/com/jfrog/ide/idea/inspections/AnnotationUtils.java
src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java
src/main/java/com/jfrog/ide/idea/inspections/InspectionUtils.java
src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
src/main/java/com/jfrog/ide/idea/inspections/ShowInDependenciesTree.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/utils/Utils.java
src/main/resources/META-INF/plugin.xml

1. Add "Show in dependencies tree" button.
2. Add "Licenses" and "Top issue" labels.
Bumped the minimal version to 2018.1 in order to fully support these features in Maven.

Add dependency information in project descriptor

---

src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java

Sometimes the Gradle dependencies tree shows:
1. [module-name]
2. [module-name].main
3. [module-name].test
In these cases we have to filter out 2 and 3.

Bugfix - Gradle '.main' and '.test' modules have to be filtered out

---

src/main/java/com/jfrog/ide/idea/GradleDependenciesDataService.java
src/main/java/com/jfrog/ide/idea/actions/RefreshAction.java
src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java

**Issue**
Currently when user makes a change in build.gradle or clicks on the "Reimport all Gradle projects" button, we tries to figure out if new modules added.
We can get a list of all Gradle modules but we can't know which one of them the user chose to import. 
Moreover, the module information we get is only partial. We only get the combined string <group>.<artifact>.
The results are duplications and redundant modules in the Dependencies tree. This causing unexpected behavior.
**Solution**
Keep the module data from the first scan and/or the last hard refresh. In soft refresh, change only the dependencies trees.

Bugfix: Gradle - don't recollect modules on soft refresh

---

src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java
src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java

Inspect "Multi project - Single module":
* Project 1 -
* Dependency 1
* Dependency 2
* Project 2
* Project 3
This fix make sure that dependencies 1 and 2 will be inspected for licenses and issues in `build.gradle`. The regular dependencies tree is not affected from this.

Improve inspection in Gradle

---

src/main/java/com/jfrog/ide/idea/scan/ScanManager.java

Projects paths are the base paths of open projects in Intellij.
We collect them from the Maven and Gradle scanners to search for go.mod and package.json files.
Calling getProjectPaths on Gradle projects return incorrect results:
```java
// Expected:
{"path/to/project/base"}
// Actual:
{"path", "to", "project", "base"}
```
This happen because `Sets.newHashSet(Path);` disintegrate the Path object to its iterable parts.
This issue may result in long searching of package.json and go.mod files in non expected locations in the file system.

Bugfix - UI on Gradle projects may freeze on start scanning

---

src/main/java/com/jfrog/ide/idea/exclusion/Excludable.java
src/main/java/com/jfrog/ide/idea/exclusion/ExclusionUtils.java
src/main/java/com/jfrog/ide/idea/exclusion/MavenExclusion.java
src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
src/main/java/com/jfrog/ide/idea/navigation/NavigationTarget.java
src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
src/main/java/com/jfrog/ide/idea/ui/issues/IssuesTree.java

Add the ability to exclude project's transitive dependencies from the Issues-Tree.
This first step applies only for Maven projects.
**Selecting the dependency to exclude:**
**Issues-tree is refreshed after exclusion:**
**pom.xml with exclusion:**

Add functionality to exclude Maven transitive dependencies from issues-tree

---

build.gradle
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
src/main/resources/META-INF/plugin.xml
src/main/resources/META-INF/with-gradle.xml
src/main/resources/META-INF/with-java.xml
src/main/resources/META-INF/with-maven.xml

Remove the obstacles to support _WebStorm_ and _GoLand_.
* Remove dependency on Java plugins by making 'maven', 'gradle', 'java' and 'groovy' plugins optional. This also will turn off inspections respectively.
* Catch `NoClassDefFoundError` when checking if Maven and Gradle are applicable. This is our sign that 'maven' or 'gradle' plugins are not installed.
* Fix the "unsupported" message.
With all of the above the plugin can work on _WebStorm_ and _GoLand_. During the next release we will be able to mark _WebStorm_ and _GoLand_ as supported in the marketplace.
**_Android Studio_**
Sadly, _Android Studio_ does not build Gradle dependencies tree as Intellij Idea does. However, this PR may take us one step forward toward supporting it in the future, as requested in #55.

Support WebStorm and GoLand

---

src/main/resources/META-INF/plugin.xml
src/main/resources/META-INF/with-java.xml

Bugfix - NoClassDefFoundError is thrown in IDEA 2020.1

---

src/main/java/com/jfrog/ide/idea/ui/listeners/IssuesTreeExpansionListener.java

- [v] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jfrog-idea-plugin) passed. If this feature is not already covered by the tests, I added new tests.
-----

Bugfix - NullPointerException is thrown when collapsing/expanding the issues-tree during a scan

---

src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/ui/issues/IssuesTree.java

Bugfix - Broken navigation from tree to descriptor after applying tree-filters

---

src/main/java/com/jfrog/ide/idea/ui/configuration/XrayGlobalConfiguration.form
src/main/java/com/jfrog/ide/idea/ui/configuration/XrayGlobalConfiguration.java

-----
Resolves #85
1. Change the default background URL text of the Xray URL from: `Example: http://localhost:8000` to `http://myjfrog.acme.org/xray`:
Before: 
After: 
2. Wrap connection results text after clicking on the test connection button.
Before: 
After:

Configuration UI form improvements

---

src/main/java/com/jfrog/ide/idea/configuration/XrayServerConfigImpl.java
src/test/java/com/jfrog/ide/idea/configuration/GetProxyConfForTargetUrlTest.java
src/test/resources/proxy/proxy.pac

-----
Support proxy configured by PAC files.

Support PAC proxy configuration

---

src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java

-----
Partially resolved #106 
Currently duplicated Maven dependencies in the same module are not shows in the dependency tree.
This PR disallows this only 2 dependencies are descendants (to avoid loops).
Before:
After:

Maven - allow duplicated dependencies in same modules

---

build.gradle

-----
In the plugin development mode, using the `runIdea` Gradle task start a new IntelliJ window with a small amount of memory. Let's increase it to 2G.

Increase max RAM to 2G in development sandbox

---

build.gradle
src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java

-----
"testSetServerConfigFromEnv", "testSetServerConfigFromLegacyEnv", and "testSetServerConfigFromXrayLegacyEnv" are tests that check the functionality of loading credentials from environment variables.
The operational code reads the environment variables using Intellij's `EnvironmentUtil.getValue()`. Probably for performance-wise in Windows, the environment map is stored in a static variable that can't be changed. Changing the system environment variables won't take effect in this case, which is the reason why the test failed.
Therefore the only way to test this functionality is using mocks.

Fix configuration tests in Windows

---

src/main/java/com/jfrog/ide/idea/ci/CiManager.java

-----
Fix an issue whereby build names contain "/", parsed incorrectly.
For example, when the build identifier is "declarative/dockerPull test/1".
Before fix: 
Build name: declarative
Build number: dockerPull test/1
After fix:
Build name: declarative/dockerPull test
Build number: 1

Support slash in build name

---

src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java

-----
Should fix this issue: https://youtrack.jetbrains.com/issue/IDEA-271019
The following error message logged on IntelliJ startup:
> Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1

Bugfix - saveSettings may occur before IntelliJ finishes loading

---

src/main/resources/META-INF/plugin.xml
src/main/resources/META-INF/with-gradle.xml
src/main/resources/META-INF/with-kotlin.xml

-----
Fix the following exception:
> java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/settings/GradleSettings
at com.jfrog.ide.idea.inspections.GradleInspection.getGradleModules(GradleInspection.java:55)
at com.jfrog.ide.idea.inspections.GradleInspection.getModules(GradleInspection.java:39)
at com.jfrog.ide.idea.inspections.AbstractInspection.getDependencies(AbstractInspection.java:160)
at com.jfrog.ide.idea.inspections.AbstractInspection.visitElement(AbstractInspection.java:50)
at com.jfrog.ide.idea.inspections.GradleGroovyInspection$1.visitLiteralExpression(GradleGroovyInspection.java:38)

Fix Gradle inspection

---

src/main/java/com/jfrog/ide/idea/ui/AbstractJFrogToolWindow.java

-----
This PR should resolve the warning message presented in #145:
> 2021-09-21 08:09:37,604 [ 68772] WARN - nSystem.impl.ActionToolbarImpl - 'JFrog toolbar' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly.

Set the target component of the ActionToolbar

---

src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java

-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/48
Send the excluded paths to the GoTreeBuilder to allow it to ignore `go.mod` files which should not be scanned.

Send the excluded paths to the GoTreeBuilder

---

src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java

-----
Gradle, npm, and Go scan managers are initialized after the findings of `build.gradle`, `package.json`, and `go.mod` files, respectfully. Adding from the UI another module should expand the search path of those files in the newly added module.

Improve multi module support in npm, Gradle and Go

---

src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java

-----
* Split to tabs
* Add explanation for projects
Connection Details tab:
Advanced tab:

Improve global configuration page

---

src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java

-----
In hard refresh, the Maven scan manager uses a terminated ExecutorService. This behavior leads to running the refresh on the same thread that waits for it to finish.

Resolve deadlock in Maven scanning

---

settings.gradle
src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java

-----
Add the ability to retrieve connection details from JFrog CLI config (if exists) by using JFrog CLI.

Get connection details from JFrog CLI 

---

src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
src/main/java/com/jfrog/ide/idea/inspections/AnnotationIconRenderer.java
src/main/java/com/jfrog/ide/idea/inspections/AnnotationUtils.java
src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java

-----
* Instead of showing red or white underlines beneath vulnerable dependencies, show the severity icon near them.
* Get rid of the meaningless records in the problems views:

Show severity icons near dependencies

---

src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
src/main/java/com/jfrog/ide/idea/inspections/GradleGroovyInspection.java
src/main/java/com/jfrog/ide/idea/inspections/GradleKotlinInspection.java
src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java

-----
Registring the `ShowInDependencyTree` problem should not occur when triggering code inspection manually A.K.A. [batch mode inspection](https://www.jetbrains.com/help/idea/running-inspections.html#run-inspections-manually).
This change is needed for 2 reasons:
1. The `ShowInDependencyTree` is not a real problem that should be shown in the code inspection.
2. Since this is an information level problem, an exception is thrown when running in batch mode, since the inspector skips them:
> com.intellij.diagnostic.PluginException: Tool #Npm registers INFORMATION level problem in batch mode on JsonFile: package.json. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, …

Disable ShowInDependencyTree in batch mode inspection

---

src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form

-----
The JFROG_IDE_URL is a legacy and should not appear in the UI. This environment variable configures Xray URL and not the platform URL. Instead, JFROG_IDE_PLATFORM_URL should be.
Before:
After:

Fix connection details from env instructions

---

src/main/java/com/jfrog/ide/idea/ui/ComponentsTree.java

-----
In a multi-project configuration, the root node should mark as metadata. Otherwise, the CSV exported will skip the projects:
https://github.com/jfrog/ide-plugins-common/blob/1.11.0/src/main/java/com/jfrog/ide/common/exporter/Exporter.java#L70

Fix generate CSV in multiproject configuration

---

build.gradle
src/main/java/com/jfrog/ide/idea/ci/CiManager.java
src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
src/main/java/com/jfrog/ide/idea/events/ApplicationEvents.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/ui/AbstractJFrogToolWindow.java
src/main/java/com/jfrog/ide/idea/ui/ComponentIssuesTable.java
src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
src/main/resources/META-INF/plugin.xml

-----
Fix the following UI issues:
* Fix an issue whereby reading credentials from CLI doesn't initiate the "More Info" panel.
* Fix an issue whereby starting a new scan doesn't reset the dependency tree and the issues table.
Update supported version from `IU-2020.3.1` to `IU-2020.3.2`, in order to handle an exception thrown in the latest macOS:
> java.lang.ClassNotFoundException: com.apple.eawt.OpenURIHandler

Better handling UI events

---

src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java

-----
Instead of scanning all Python SDKs, scan only the Python SDK of the selected Python interpreter.

Show only Python dependencies of the selected interpreter

---

src/main/java/com/jfrog/ide/idea/log/Logger.java

-----
Avoid popup to the "IDE Fatal Error", such as:
All errors are still logged in the regular event log of the plugin, with their log level.

Avoid popup on fatal errors

---

src/main/java/com/jfrog/ide/idea/scan/ScanManager.java

-----
Fix the following exception:
> IllegalArgumentException: 'other' is different type of Path
java.lang.IllegalArgumentException: 'other' is different type of Path
at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400)
at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
at com.jfrog.ide.idea.scan.ScanManager.getTaskTitle(ScanManager.java:197)
at com.jfrog.ide.idea.scan.ScanManager.asyncScanAndUpdateResults(ScanManager.java:157)
at com.jfrog.ide.idea.scan.ScanManagersFactory.startScan(ScanManagersFactory.java:99)
at com.jfrog.ide.idea.scan.ScanManagersFactory.lambda$registerOnChangeHandlers$0(ScanManagersFactory.java:69)

Fix IllegalArgumentException in some scenarios

---

build.gradle
src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
src/test/java/com/jfrog/ide/idea/scan/GradleScanManagerTest.java

-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/77 & https://github.com/jfrog/gradle-deps-tree/pull/1
New features:
1. Better accuracy - use the same APIs as `gradle dependencies` task does. The dependency tree should contain a more detailed view of Gradle configurations.
2. Performance -
a. Unlike before, the task runs on each subproject exactly once.
b. Use task cache. The cache is stored in the `${buildDir}/gradle-deps-tree` and invalidated if there was a change in the Gradle project.

Improve Gradle projects scanning

---

src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java

-----
Fixes https://github.com/jfrog/jfrog-idea-plugin/issues/231#issuecomment-1291760356
Fix the following issue when trying to save a watch with ".":\

Bugfix - Illegal chars error when using a watch with period

---

src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/YarnScanManager.java

-----
Resolve #231 
The NavigationService gets populated after the code inspection. Code inspections may run after one of the 3 following options:
1. The project descriptor (like pom.xml) was opened.
2. The user manually triggered code inspection by clicking on "Code | Inspect Code" - we intentionally skip our code inspections in this case (see https://github.com/jfrog/jfrog-idea-plugin/pull/186).
3. An Xray scan was completed - we accidentally skip code inspections in this case.
This PR makes sure that in the 3rd option, the code inspections are not skipped.

Bugfix - code inspection does not run after an Xray scan

---

src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java

-----
Fix the following exception:
```
com.intellij.diagnostic.PluginException: Tool #Maven (class com.jfrog.ide.idea.inspections.MavenInspection) registers 'INFORMATION'-level problem in batch mode on XmlFile:pom.xml. Warnings of the 'INFORMATION' level are invisible in the editor and should not become visible in batch mode. Moreover, since 'INFORMATION'-level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations [Plugin: org.jfrog.idea]
at com.intellij.codeInspection.InspectionEngine$2.registerProblem(InspectionEngine.java:261)
at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:52)
```
After an Xray scan, we trigger inspections on the project descriptors, to allow navigating from …

Fix exception from Inspector

---

src/main/java/com/jfrog/ide/idea/actions/RefreshLocalAction.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java

-----
When a user clicks on the "Refresh Scan" button, read Xray scan results from caches rather than sending REST requests to Xray every time.
This should reduce the load on either server side and dramatically improve the performance of the "Refresh Scan" button.
After this change, we will send a REST to the Xray server in one of the following scenarios:
1. Changing the server configuration (like changing the server URL or the Watch) 
2. If a dependency is invalidated (older than 1 week)

Read from cache when triggering a scan by the "Refresh Scan" button

---

.github/workflows/test.yml
src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
src/test/java/com/jfrog/ide/idea/configuration/ConnectionDetailsFromCliTest.java

-----
Depends on: https://github.com/jfrog/ide-plugins-common/pull/87
In the following use-case, reading credentials from the JFrog CLI cause infinite recursion:
1. Delete credentials in JFrog IDEA plugin configuration.
2. Configure default JFrog CLI server with Artifactory URL only: 
`jf c add --artifactory-url=https://acme.jfrog.io/artifactory --user=frogger --password=super-secret`
3. Trigger Xray scan in the JFrog IDEA plugin.
Results:
> java.lang.StackOverflowError
at java.base/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:382)
at java.base/java.util.concurrent.SynchronousQueue.offer(SynchronousQueue.java:909)
at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1347)
at …

Bugfix - Stackoverflow when reading credentials from CLI

---

src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java

-----
Reverted using a map in LocalComponentsTree. Using a map caused files with the same name to not being added to the results tree. The tree wasn't necessary so it was reverted, and we use a list instead.

Fix missing files in results

---

src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java

-----
**Problem**
Currently in python, when there is an unresolved dependency, we add `[Unresolved]` suffix in the component ID. The problem is that this prefix is sent to Xray. As a result, Xray returned an unexpected result.
**Solution**
This PR fixes this issue by removing the `[Unresolved]` suffix from the dependency tree. 
**Justifications**
1. The new UI doesn't show the dependency tree and it is confusing to display `[Unresolved]` only in the vulnerable components.
2. We will find a better way to display not-installed projects.

Incorrect fixed versions in Poetry

---

src/main/java/com/jfrog/ide/idea/utils/Utils.java

-----
Fixes usage report sending when authentication is done with an access token.

Support  usage report with access token

---

src/main/java/com/jfrog/ide/idea/utils/Utils.java

-----
Fixes usage report sending when authentication is done with an access token.

V1 : Support usage report with access token

---

build.gradle
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
src/test/java/com/jfrog/ide/idea/scan/ScanManagersTest.java

-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/248
Depends on https://github.com/jfrog/ide-plugins-common/pull/101
When changing watches, the cache does not get updated.
This PR changes the way we initialize the scan cache in case of a full scan, by avoiding reading the cache from the file system.

V1: Skip loading cache from file-system in full scan mode

---

build.gradle
src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java

V1: Watches are ignored when reading creds from env

---

src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java

-----
Same as https://github.com/jfrog/jfrog-idea-plugin/pull/267

Watches are ignored when reading creds from env

---

build.gradle
gradle.properties

-----
After updating the Webview version, Gradle will update the expected sha256 of the Webview when running locally.

Automatically update the Webview checksum

---

build.gradle
src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
src/main/java/com/jfrog/ide/idea/ui/IssuesTableSelectionListener.java
src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java

-----
Added the option to create ignore rule in the right-click context menu.
Fixes https://github.com/jfrog/jfrog-idea-plugin/issues/238
Depends on https://github.com/jfrog/ide-plugins-common/pull/103
After right-click:
When no project/watch was configured so the ignore rule cannot be created:

Allow creating ignore rules to specific violation 

---

src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java

-----
This PR fixes 2 bugs related to the excluded paths config param:
- Set the field with default excluded paths by default.
- Fix the conversion of the excluded paths param, so the applicability scanners will work if an empty pattern is configured.

Fix Default Excluded Paths

---

build.gradle
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java

-----
Detect and suggest a solution for an inactive JFrog platform (free-tier).
Fixes https://github.com/jfrog/jfrog-idea-plugin/issues/228
Depends on https://github.com/jfrog/xray-client-java/pull/42, https://github.com/jfrog/build-info/pull/698

Add Inactive Jfrog platform handling (free-tier)

---

build.gradle
src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/Eos.java
src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
src/main/java/com/jfrog/ide/idea/scan/data/Region.java
src/main/java/com/jfrog/ide/idea/scan/data/SarifResult.java
src/main/java/com/jfrog/ide/idea/utils/Utils.java
src/test/java/com/jfrog/ide/idea/ServerConfigStub.java
src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
src/test/resources/applicability/not_applic_output.sarif
src/test/resources/applicability/simple_output.sarif

-----
This PR adds support for downloading the new AnalyzerManager.
As well as adapting the SARIF parsing to the new AnalyzerManager output.

Add support for Downloading  the AnalyzerManager

---

src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java

Fix - The applicability scan is irrelevant if no CVES were found.

---

build.gradle
src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java

-----
When cached results are shown, inspections didn't run yet, so navigation is not available.

Disable navigation from cached results

---

src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
src/test/java/com/jfrog/ide/idea/scan/SourceCodeManagerTest.java

-----
Add the missing "*/**" to the Applicability skip folders pattern.

Fix applicability scan exclude directories 

---

README.md

-----
Added an explanation in the README about Android Studio not supporting JCEF by default and a solution to this issue.

JCEF issue reference in the README

---

build.gradle
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
src/main/java/com/jfrog/ide/idea/utils/Utils.java

-----
Depends on: https://github.com/jfrog/ide-plugins-common/pull/114

Add new "empty state" for scan interruptions and improve error handling

---

src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java

-----
Wrap the browser component in a Panel to fix display issues in some versions of IntelliJ in Windows.

Fix display issues in Windows

---

src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewResourceHandler.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewSchemeHandlerFactory.java

-----
Read web resources directly from the JAR, without copying them to a temporary directory first.
Stream the browser's console messages to the plugin's logger.

Read webview resources directly from the JAR

---

src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java

-----
Fix IndexNotReadyException when reading cached results. Inspections will be run after indexing is done.

Fix IndexNotReadyException on plugin startup

---

src/main/java/com/jfrog/ide/idea/ui/JfrogContextMenuHandler.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java

-----
This pull request introduces the display of separate DevTools. Users can access the DevTools window by right-clicking on Webview and selecting the 'Inspect' option.

Webview - Add DevTools window

---

build.gradle
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
src/main/java/com/jfrog/ide/idea/utils/Utils.java

-----
Depends on: https://github.com/jfrog/ide-plugins-common/pull/127, https://github.com/jfrog/build-info/pull/751
Should  fix https://github.com/jfrog/jfrog-idea-plugin/issues/34#issuecomment-1651042810

Use SSLContext when sending usage report

---

src/main/java/com/jfrog/ide/idea/utils/GoUtils.java

-----
Fix error thrown when no modules are configured in the project.

Fix error when Go project has no modules

---

src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java

-----
Fix the following issue:
> 2023-08-17 14:04:20,412 [509832340]   WARN - #com.jfrog.ide.idea.log.Logger - Xray scan failed: ConcurrentModificationException: 
java.util.ConcurrentModificationException
at java.base/java.util.Vector$Itr.checkForComodification(Vector.java:1298)
at java.base/java.util.Vector$Itr.next(Vector.java:1254)
at com.jfrog.ide.idea.scan.SourceCodeScannerManager.mapDirectIssuesByCve(SourceCodeScannerManager.java:275)
at com.jfrog.ide.idea.scan.SourceCodeScannerManager.applicabilityScan(SourceCodeScannerManager.java:69)
at com.jfrog.ide.idea.scan.ScannerBase.scanAndUpdate(ScannerBase.java:157)
at com.jfrog.ide.idea.scan.ScannerBase$1.run(ScannerBase.java:295)
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
at …

Fix ConcurrentModificationException in SourceCodeScannerManager

---

src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java

-----
The Analyzer Manager has been updated to 1.2.4.1921744, which adds the ability to suppress false positive secrets detection by adding `jfrog-ignore` phrase above the unwanted result line.

Update AnalyzerManager to version 1.2.4.1921744

---

build.gradle

-----
The following Null Pointer Exception  was thrown as a result of changing the FileIssueNode data object without updating the cache version:
```
com.intellij.diagnostic.PluginException: annotator: com.jfrog.ide.idea.inspections.JFrogSecurityAnnotator@7515b1ba (class com.jfrog.ide.idea.inspections.JFrogSecurityAnnotator) [Plugin: org.jfrog.idea]
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:251)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:227)
at …
```

Fix NPE when reading results from cache 

---

src/main/java/com/jfrog/ide/idea/scan/GoScanner.java
src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java

-----
Print to log in case of trying to run inspections on a Go project while the Go plugin is disabled or not installed.

Fix PluginException thrown if the Go plugin is not installed

---

src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
src/main/resources/META-INF/plugin.xml

-----
Migrating the GlobalSettings component (which is deprecated) to an application service. This should eliminate the need to restart the IDE after installation or updates.

Migrating GlobalSettings component to a service

---

src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java

-----
Due to the addition of multiple scanners that use the same binary (AnalyzerManager) to scan the project. It is possible that more than one scanner will initiate the binary download flow which may cause one of the multiple scans to fail.
This PR suggests limiting the number of possible download attempts to 1.

Allow only one thread to update the AnalyzerManager binary at any time

---

src/main/java/com/jfrog/ide/idea/scan/EosScannerExecutor.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
src/main/java/com/jfrog/ide/idea/ui/webview/event/tasks/JumpToCodeTask.java

-----
When clicking on the ' Analysis steps`(CodeFlows) section on the right pane, it highlights the wrong source code section in the editor. The jump-to-code implementation should consider the difference between the displayed line and col indexes to the file accurate indexes.

Fix EOS CodeFlows Jump to code

---

src/main/java/com/jfrog/ide/idea/actions/StartLocalScanAction.java
src/main/java/com/jfrog/ide/idea/events/AnnotationEvents.java
src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
src/main/java/com/jfrog/ide/idea/ui/JFrogFloatingToolbar.java

-----
When the source code no longer matches the scan results, suggest re-scan by showing our `JFrog floating toolbar`.

Show floating toolbar when results don't match source code

---

src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java

-----
The scanner's run logs will now be logged in the IDE log instead of in a dedicated log file.
If an error occurs the log level is `INFO`, otherwise `DEBUG`.

Improve source code scanners logging

---

src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java

-----
Ignore ERR_ABORTED errors caused because JBCef cancels redirections when opening in an external browser.

Fix ERR_ABORTED when opening links

---

src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java

Fix InterruptedException in projects with large dependency trees

---

build.gradle

-----
In some cases when the Windows user name included spaces, we were not able to run some of our source code scanners. 
This PR introduced the use of the new version of our build-info dependency (2.41.6) which includes a fix for this issue.

Fix - Scanners Failing to Run on Windows Due to Username Spaces

---

src/main/java/com/jfrog/ide/idea/actions/StopLocalScanAction.java
src/main/java/com/jfrog/ide/idea/events/ApplicationEvents.java
src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
src/main/resources/META-INF/plugin.xml

-----
This PR adds a new abort all scan's task option.

Add Abort Scan button 

---

src/main/java/com/jfrog/ide/idea/utils/Utils.java

-----
Removed the plugin version from the product ID in the Ecosystem usage reports.

Change product ID in Ecosystem usage reports

---

.github/workflows/integration-tests.yml
.github/workflows/test.yml
.github/workflows/verification.yml
build.gradle
src/main/java/com/jfrog/ide/idea/inspections/AnnotationIconRenderer.java
src/main/java/com/jfrog/ide/idea/inspections/GradleKotlinInspection.java
src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
src/main/java/com/jfrog/ide/idea/ui/ComponentIssueDetails.java
src/main/java/com/jfrog/ide/idea/ui/ComponentsTreeCellRenderer.java
src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
src/main/java/com/jfrog/ide/idea/ui/menus/filtermenu/FilterMenu.java
src/main/java/com/jfrog/ide/idea/utils/Descriptor.java
src/main/java/com/jfrog/ide/idea/utils/Utils.java
src/main/resources/META-INF/plugin.xml
src/test/java/com/jfrog/ide/idea/integration/IACScannerIntegrationTests.java
src/test/java/com/jfrog/ide/idea/integration/SecretsScannerIntegrationTests.java

-----
Use the Apache Commons Lang dependency directly, instead of calling the one used by IntelliJ (it's already directly imported, but was used only in part of its usages).

Fix compatibility problems in future IntelliJ releases

---

src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/IACScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/SastScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
src/main/java/com/jfrog/ide/idea/scan/SecretsScannerExecutor.java
src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
src/main/java/com/jfrog/ide/idea/scan/data/ScanConfig.java
src/test/java/com/jfrog/ide/idea/integration/ApplicabilityScannerIntegrationTests.java
src/test/java/com/jfrog/ide/idea/integration/ExternalResourcesRepoIntegrationTests.java
src/test/java/com/jfrog/ide/idea/integration/IACScannerIntegrationTests.java
src/test/java/com/jfrog/ide/idea/integration/SecretsScannerIntegrationTests.java

JAS scanners  - Remove timeout & Enhance progress bar and include additional logging

---

src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java

-----
* Verification code added to SSO login process.

Introducing Verification Code for SSO Login

---

release/pipelines.release.yml
release/pipelines.snapshot.yml

Fix release

---

build.gradle

-----
Update build-info version to 2.41.13
JAS scanners are not running on Windows machines where the user name has space in there name.
Updating build-info version to apply the fix for this issue: https://github.com/jfrog/build-info/pull/777

Fix running executables with spaces in their paths in Windows

---

src/main/java/com/jfrog/ide/idea/actions/ScanTimeLabelAction.java

-----
The ActionUpdateThread has a deprecated func called getActionUpdateThread.
We override it so we wont use the deprecated func that pops errors for all our users.
Is this case, the function should return `EDT`(Event Dispatch Thread) , as the current process affects the ui text. 
This is not needed in other places in the code as it is already being override in all places.

Override a deprecated func to prevent unnecessary errors

---

build.gradle

-----
This PR updates the config in the build gradle for verify plugin command.
Instead of checking the plugin on every version of IDEA, and running up the runner space, it now checks only on the oldest(as described in the project) and newest versions of IDEA.

Configured the verify plugin command 

---

src/main/java/com/jfrog/ide/idea/scan/SastScannerExecutor.java
src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java

-----
I switched the title of SAST warnings to the `reason` instead of `ruleId`

Rule id is shown in warning title

---

src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java

-----
The title in the webview became the description. this obviously isn't good for anything as it is not the right pararmater.

Fixed the title for warnings in webview

---

src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java

-----
Created a function to determine the reason according to scanner type, as when the scan is of SAST, we take the short description

Changed the SAST title to the short description rule

---

src/main/java/com/jfrog/ide/idea/scan/MavenScanner.java
src/main/java/com/jfrog/ide/idea/scan/SingleDescriptorScanner.java

-----
Added handeling for cases where the project itself is a violation (for example rule on licenses that the project itself violates),
now when we group to descriptors, we check if the vulnerable dependency is part of the root of the descriptor.
if so, we add it appropriately.

Project declaration itself triggers a violation from xray

---

src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
src/test/java/com/jfrog/ide/idea/scan/PypiScannerTest.java

-----
We only support HTTP proxy for now as JetBrains does not give indication if proxy is HTTP or HTTPS
when moving to CLI, we will create a ping function to determine if proxy is HTTP or HTTPS
Also fixed python test

Fix Analyzer Manager proxy
