jfrog/jfrog-idea-plugin

- .travis.yml
- README.md
- appveyor.yml
- build.gradle
- Fix tests - Change 'groovy' to 'Groovy'.
- Migrate macOS tests to Appveyor.
- Remove Travis tests.
- Upgrade Intellij Gradle plugin.
> Fix tests, add macOS to Appveyor and remove Travis tests

- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
* Add modules under their parent module in additional to the root tree - if module B is a sub module of A it will appear either in the root and **also** under A's tree. 
(https://github.com/jfrog/jfrog-idea-plugin/commit/1e5b4d10c05db5cb57ae8da260b177a294b53ec5#diff-52e41abbf98592f7f619fdfa9fcfeb78L130)
* Add loop prevention mechanism - Module A -> Module B -> Module A -> ...
(https://github.com/jfrog/jfrog-idea-plugin/commit/1e5b4d10c05db5cb57ae8da260b177a294b53ec5#diff-52e41abbf98592f7f619fdfa9fcfeb78R110 & https://github.com/jfrog/jfrog-idea-plugin/commit/1e5b4d10c05db5cb57ae8da260b177a294b53ec5#diff-52e41abbf98592f7f619fdfa9fcfeb78R149)
This scenario split to 2 sub cases.
In the following test cases, `multi3` is a sub module of `multi1`:
In the following test cases, `multi3` is a …
> Maven - show modules under their parent

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
* Add PR template
* Add Issues templates
* Bug report
* Feature request
* question
> Add GitHub issues and PR templates

- src/main/java/com/jfrog/ide/idea/ui/configuration/XrayGlobalConfiguration.java
- [v] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jfrog-idea-plugin) passed. If this feature is not already covered by the tests, I added new tests.
-----
> Configuration page - restore previously set credentials when selection changes on environment-variables checkbox

- build.gradle
- src/main/resources/META-INF/plugin.xml
- [v] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jfrog-idea-plugin) passed. If this feature is not already covered by the tests, I added new tests.
-----
> Update ide-plugins-common version and release-notes

- build.gradle
- src/main/java/com/jfrog/ide/idea/gradle/GradleDependenciesDataService.java
- src/main/java/com/jfrog/ide/idea/inspections/AnnotationUtils.java
- src/main/java/com/jfrog/ide/idea/projects/ProjectBase.java
- src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/issues/IssuesTreeCellRenderer.java
- src/main/java/com/jfrog/ide/idea/ui/licenses/LicensesTreeCellRenderer.java
- src/main/resources/META-INF/plugin.xml
> Increase plugin's minimum supported IDEA version to 2020.1.2 + Fix Gradle-plugin's compatibility

- Jenkinsfile
> Changed credentials and jdk

- src/main/java/com/jfrog/ide/idea/ui/filters/FilterMenu.java
- src/main/java/com/jfrog/ide/idea/ui/filters/MenuCheckbox.java
- src/main/java/com/jfrog/ide/idea/ui/filters/SelectAllCheckbox.java
- src/main/java/com/jfrog/ide/idea/ui/filters/SelectionCheckbox.java
> Uncheck 'All' filter on start when there is an active filter

- src/main/java/com/jfrog/ide/idea/navigation/NavigationTarget.java
> Fix PsiInvalidElementAccessException in NavigationTarget

- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
> Improve description for excluded paths

- build.gradle
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
-----
Precondition: https://github.com/jfrog/artifactory-client-java/pull/303
> Support SSL certificates in Artifactory client

- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
-----
HashMultimap uses the default hash and equals functions of ArtifactDependencyNodeImpl. Using these defaults causes duplications in the dependency tree. Moreover, using equals and hash of ArtifactDependencyNodeImpl compares children as well, and we need only to compare the GAV string of a node.  
Therefore we would prefer to use TreeMultimap with custom compare functions.
Before:
After:
> Bugfix: Gradle dependency tree duplications

- src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
> Update component details view on CI conf change

- src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
> Update "No builds detected" link

- build.gradle
- src/main/resources/META-INF/plugin.xml
> Upgrade ide-plugins-common and update change-notes

- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
> Build scan does not properly canceled

- README.md
> Update release notes link

- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
> Fix success Artifactory connection message

- build.gradle
- src/main/resources/META-INF/plugin.xml
> Update ide-plugins-common and release notes

- src/main/resources/META-INF/plugin.xml
> Add release notes and change description

- build.gradle
- src/main/java/com/jfrog/ide/idea/log/Logger.java
- src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
- src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
- src/main/resources/META-INF/plugin.xml
-----
Should be merged after 1.9.0 release.
> Support the latest Intellij platform release

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
-----
Update README badge and PR template.
> Complete migration to GitHub actions

- src/main/java/com/jfrog/ide/idea/actions/RefreshBuildsAction.java
- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
- src/main/java/com/jfrog/ide/idea/log/Logger.java
- src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java
- src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
-----
Depends on: https://github.com/jfrog/ide-plugins-common/pull/39
> Popup balloons only on interactive scans

- build.gradle
-----
* Remove oss.jfrog.org.
* Download dependencies from Maven Central and releases.jfrog.io
> Download dependencies from releases.jfrog.io

- build.gradle
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
- src/main/resources/META-INF/plugin.xml
> Update dependencies and change notes

- build.gradle
- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
- src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
- src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
- src/main/java/com/jfrog/ide/idea/log/ProgressIndicatorImpl.java
- src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentsTreeCellRenderer.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
- src/main/java/com/jfrog/ide/idea/utils/Utils.java
- src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
> Add  support for new  Xray graph scan API

- src/main/java/com/jfrog/ide/idea/log/Logger.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/46
Resolves #141 and possibly #142
> Use Gradle executable and JAVA_HOME from preferences

- src/main/resources/META-INF/plugin.xml
> Add release notes

- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
> BugFix: Cache for Multi Projects/Modules

- src/main/java/com/jfrog/ide/idea/events/ApplicationEvents.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
> Recreate scan managers upon change in excluded paths

- src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
- src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java
- src/test/java/com/jfrog/ide/idea/inspections/GradleInspectionTest.java
-----
Implement @eyalbe4 suggestions on https://github.com/jfrog/jfrog-idea-plugin/pull/165.
> Reduce tree memory consumption - follow up

- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
-----
* Make sure the countdown latch always counts down by invoking it in the task's `onFinished`.
* Bugfix - Scan initiated by a change in the project descriptor uses a terminated executer service.
> Improve executor service algorithm

- src/main/resources/META-INF/plugin.xml
> Add release notes for the next release

- src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
- src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
> Add access token support

- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
- src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
- src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
- src/main/java/com/jfrog/ide/idea/utils/Utils.java
> Add Usage Report Sending 

- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
-----
After a change in `go.sum` or `package-lock.json`, an automatic scan is triggered. In this case, we don't have an ExecutorService, and therefore the running thread may be the UI. running `latch.await()` freezes the running thread until `latch.countDown()` is called. However in this case we have only 1 running thread.
To overcome this issue, we can waive the `latch.await()` and let the UI thread to finish. This PR implements this logic by providing latch=null.
> Resolve deadlock in Go and npm scanning

- src/main/resources/META-INF/plugin.xml
> Update release notes

- src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
> Improve welcome view

- src/main/java/com/jfrog/ide/idea/log/ProgressIndicatorImpl.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
> Improve progress indicator

- src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
- src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogProjectConfiguration.form
- src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java
- src/test/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtilsNegativeTest.java
- src/test/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtilsPositiveTest.java
-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/68 & https://github.com/jfrog/xray-client-java/pull/30
> Support Xray watches

- build.gradle
- settings.gradle
- src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
- src/main/java/com/jfrog/ide/idea/ui/AbstractJFrogToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentDetails.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentIssueDetails.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentIssuesTable.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentsTree.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentsTreeCellRenderer.java
- src/main/java/com/jfrog/ide/idea/ui/IssueDetails.java
- src/main/java/com/jfrog/ide/idea/ui/IssuesTableCellRenderer.java
- src/main/java/com/jfrog/ide/idea/ui/IssuesTableModel.java
- src/main/java/com/jfrog/ide/idea/ui/IssuesTableSelectionListener.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/MoreInfoPanel.java
- src/main/java/com/jfrog/ide/idea/ui/components/ImpactPathPane.java
- src/main/java/com/jfrog/ide/idea/ui/components/ReferencesPane.java
- src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
- src/main/java/com/jfrog/ide/idea/utils/Utils.java
-----
Dependent Pull Requests:
* https://github.com/jfrog/build-info/pull/611 
* https://github.com/jfrog/xray-client-java/pull/31
* https://github.com/jfrog/ide-plugins-common/pull/69
Add the following features:
* Move the upper component details panel to the right
* Introduce impact path graph
* Make CVE a list
* Add expandable references links
* Add "Create Ignore Rule" action on right-click on the issue (if applicable):
> Introduce new UI

- src/main/resources/META-INF/plugin.xml
> Update plugin description

- src/main/java/com/jfrog/ide/idea/ui/ComponentIssuesTable.java
- src/main/java/com/jfrog/ide/idea/ui/IssuesTableSelectionListener.java
-----
Allow selecting an issue in the issue table using the up and down arrows. The issue selection shows the issue details in the "More Info" panel.
> Allow selecting issues using the keyboard arrows

- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
- src/main/java/com/jfrog/ide/idea/events/BuildEvents.java
> Bugfix - handle build number with colon (":")

- src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
-----
Fix a minor issue introduced in https://github.com/jfrog/jfrog-idea-plugin/pull/219
> Fix title in progressbar

- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
> Fix tooltips for URLs

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- release/pipelines.release.yml
- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
- src/main/java/com/jfrog/ide/idea/log/Logger.java
- src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
- src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
- src/main/java/com/jfrog/ide/idea/ui/CiComponentsTree.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java
- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
- src/main/java/com/jfrog/ide/idea/ui/menus/filtermanager/CiFilterManager.java
- src/main/java/com/jfrog/ide/idea/ui/menus/filtermanager/LocalFilterManager.java
- src/main/java/com/jfrog/ide/idea/ui/utils/IconUtils.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/jfrog/ide/idea/scan/GradleScanManagerTest.java
-----
* Update the minimal IntelliJ IDEA version to 2021.3
* Update Gradle to 6.9.3 and remove legacy configurations
* Replace deprecated methods
> Modernize plugin

- build.gradle
- settings.gradle
- src/main/resources/META-INF/plugin.xml
-----
Fix #239
Use the solution suggested here: https://youtrack.jetbrains.com/issue/IDEA-298989
> Unable to configure the plugin

- .github/workflows/frogbot-scan-pull-request.yml
> Add Frogbot to this repository

- src/main/java/com/jfrog/ide/idea/ui/configuration/ConnectionTimeoutSpinner.java
> Increase default connection timeout to 5 minutes

- webview/package-lock.json
> Webview container package-lock.json update

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Fix windows applicability scan

- src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
> Fix JFrogSecurityAnnotator NullPointerException

- build.gradle
- src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
- src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
- src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
- src/main/java/com/jfrog/ide/idea/scan/data/Message.java
- src/main/java/com/jfrog/ide/idea/scan/data/Rule.java
- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/99
> Added ScannerSearchTarget info for the contextual analysis view

- src/main/java/com/jfrog/ide/idea/utils/Utils.java
> Close Xray client after getting the Xray version

- src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
-----
Reverted a try/catch block that handled missing plugins.
> Handle Gradle plugin not installed

- build.gradle
- src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePacker.java
- src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePipe.java
- src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePipeSupport.java
- src/main/java/com/jfrog/ide/idea/ui/jcef/message/PackedMessage.java
- src/main/java/com/jfrog/ide/idea/ui/webview/model/DependencyPage.java
> Upgrade webview to 0.1.16

- src/main/java/com/jfrog/ide/idea/ui/webview/model/DependencyPage.java
> Restore pageType property in DependencyPage class

- src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePacker.java
> Add a log message to the Webview message data

- build.gradle
- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
- src/main/java/com/jfrog/ide/idea/ui/webview/model/DependencyPage.java
- src/main/java/com/jfrog/ide/idea/ui/webview/model/ImpactGraph.java
> Upgrade webview to v0.1.18

- src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
- src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
- src/main/java/com/jfrog/ide/idea/navigation/NavigationTarget.java
- src/main/java/com/jfrog/ide/idea/ui/ComponentsTree.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> Reimplement jump from tree to editor

- src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Replace Applicability scanner with analyzerManager

- build.gradle
-----
Include the following fixes:
* https://github.com/jfrog/ide-plugins-common/pull/107
* https://github.com/jfrog/gradle-dep-tree/pull/6
> Support Gradle 7.6

- build.gradle
> Update build-info to 2.39.1

- src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
> Remove close button in the ignore rule popup

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
The source code scanner should receive the latest connection details before each run.
> Apply Connections details change between source code scanners runs

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
This PR fixes the checksum calculation of the remote AnalyzerManager.zip.
As well as handles the analyzerManger logs.
> Fix analyzer manager download

- gradle.properties
> Update Webview to 0.1.20

- build.gradle
> Upgraded ide-plugins-common

- src/main/resources/META-INF/plugin.xml
> Updated change notes

- src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> Add expiry of 7 days for scan cache files

- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
> Rename isCacheValid to isCacheExpired

- build.gradle
- src/main/resources/META-INF/plugin.xml
> Release preparations

- src/main/resources/META-INF/plugin.xml
> Update the plugin description

- .github/workflows/integration-tests.yml
> Change "IntegrationTests" to "Integration Tests"

- build.gradle
- gradle.properties
> Upgrade web view to version 0.1.21

- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
> NPE when SeverityReasons are missing from vulnerability

- src/main/java/com/jfrog/ide/idea/scan/MavenScanner.java
-----
* Remove non-used Maven dependencies according to the Maven plugin in IntelliJ IDEA.
* The state of the Maven artifact can be one of the following: ADDED, EXCLUDED, CONFLICT, DUPLICATE, CYCLE.
Since we already know if the artifact is under a DUPLICATE state, we can delete the "added" set that it purpose was to remove duplications.
> Remove omitted dependencies in Maven

- .github/workflows/test.yml
- README.md
- build.gradle
- gradle.properties
- src/main/java/com/jfrog/ide/idea/scan/PypiScanner.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/jfrog/ide/idea/TestUtils.java
- src/test/java/com/jfrog/ide/idea/scan/DummyCircularDepSDK.java
- src/test/java/com/jfrog/ide/idea/scan/DummyCircularRequirement.java
- src/test/java/com/jfrog/ide/idea/scan/PypiScannerTest.java
-----
This PR Should fix https://github.com/jfrog/jfrog-idea-plugin/issues/318.
It also introduces a new test suite for Python.
> Handle python tree with circular dependencies

- build.gradle
- src/main/java/com/jfrog/ide/idea/utils/Utils.java
-----
Depends on: https://github.com/jfrog/build-info/pull/717
> Add new client ID usage reporter

- build.gradle
- src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/115
> Fix missing data in applicability cached objects 

- CONTRIBUTING.md
- README.md
> Update README and add new contributing.md

- build.gradle
- src/main/resources/META-INF/plugin.xml
> Upgrade dependencies and change notes

- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
-----
* Creating the browser component when the tool window is created.
* Nicer way to open links in an external browser.
> Load the issue details view in advance

- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
-----
Adds new indication for missing URLs after clicking on the test connection button:
> Test connection - add indication for missing URL

- src/main/resources/META-INF/plugin.xml
> Change notes update

- src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
- src/main/java/com/jfrog/ide/idea/inspections/YarnInspection.java
- src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
- src/main/resources/META-INF/plugin.xml
-----
Fix IndexNotReadyException when reading cached results.
Fix YarnInspection not running on startup.
> Fix inspection errors on startup

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Set fixed version for Analyzer Manager binary 

- build.gradle
- src/main/resources/META-INF/plugin.xml
> Change notes and dependencies update

- src/main/java/com/jfrog/ide/idea/ui/webview/model/Location.java
> Webview 0.2.1 Location object - Replace "row" with "startRow"

- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
-----
Fixed IaC result display as green loading image instead of detailed data.
> Fix IaC WebView display

- src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
> Add Java Contextual Analysis Support

- .github/workflows/integration-tests.yml
-----
Fixed integration tests being skipped in pull requests.
> Fix integration tests not running in pull requests

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Upgrade Analyzer Manager Version to 1.2.4.1858388

- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
> Set min SSO version hint to 7.64.0

- build.gradle
- src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
- src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
-----
Fix applicability info is sometimes not shown and not saved in cache properly.
> Fix applicability info not shown

- .github/workflows/integration-tests.yml
- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
Use JFrog Releases to download the AM
> Fix integration tests

- src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
- src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
- src/test/resources/applicability/not_applic_output.sarif
- src/test/resources/applicability/simple_output.sarif
-----
Fix converting file paths in Windows.
> Fix converting file paths in Windows

- src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
-----
Ignore false secret issues.
> Ignore false secret issues

- gradle.properties
-----
Upgraded webview to 0.2.8.
> New UI for the vulnerability details view

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
Adds the new SAST scanner.
Bug fixes and improvements for other scanners.
> Upgrade Analyzer Manger to version 1.3.2.2005632

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Bug fixes and improvements
-----
Bug fixes and improvements for the source code scanners.
> Upgrade Analyzer Manger to version 1.3.2.2006984

- src/main/java/com/jfrog/ide/idea/ci/CiManager.java
> Fix build not found error in CI tab

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Bug fixes and improvements to the SAST scanner.
-----
> Update Analyzer Manager version to 1.3.2.2019257

- src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/UpgradeVersion.java
> Fix errors in quick fix of vulnerable Maven dependencies

- build.gradle
> Update ide-plugins-common to v2.2.6

- build.gradle
- settings.gradle
- src/main/java/com/jfrog/ide/idea/utils/Utils.java
-----
Depends on https://github.com/jfrog/ide-plugins-common/pull/139
> Use the new Ecosystem Usage Reporter

- src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
- src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
> Add .git to default exclusions

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Update Analyzer Manager version to 1.4.0

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Analyzer manager version update to 1.6.0

- build.gradle
> Dependency Upgrade: ide-plugins-common

- src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
-----
* "TreeUI should be accessed only from EDT" error does not appear again.
* minor changes - reduced warnings in codefile.
> Resolved TreeUI Error

- release/pipelines.release.yml
- release/pipelines.snapshot.yml
> Fix release

- release/pipelines.release.yml
- release/pipelines.snapshot.yml
> Release automation - temporary remove resolution repo

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Analyzer manager updated to version 1.6.3

- build.gradle
> Fixed Go Issue in Windows with executable path containing spaces

- gradle.properties
- src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
- src/main/java/com/jfrog/ide/idea/ui/webview/event/Receiver.java
- src/main/java/com/jfrog/ide/idea/ui/webview/event/model/IdeEvent.java
> Upgrade webview to v0.2.14

- src/main/java/com/jfrog/ide/idea/scan/SastScannerExecutor.java
-----
Now we take the full description instead of the reason
> Fixed the description of SAST issues

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
> Updated AM version to 1.9.9

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
- Upgrade Analyzer Manager version to 1.13.4.
> upgrade AM version to 1.13.4

- .github/workflows/verification.yml
- build.gradle
- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
- src/main/resources/META-INF/plugin.xml
> Updated am version to 1.15.2

- src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
-----
Upgraded AM version to `1.20.1`
> Upgrade Analyzer Manager version to 1.20.1

- release/pipelines.release.yml
-----
made jf audit optional for releases
will run in default
> Updated jf audit in release to be optional
